import Head from 'next/head'
import Intro from '../components/Intro'
import Services from '../components/Services'
const clientId = 'Fn3yNj9x3TeI8mbR1H6pUvwrYkGeo6tJIjKhjHhK81Y7O6QfhZ'
const clientSecret = 'MuCuL3EIUZR6XvplrjDW6VKQd8bYO9owxnP8RZX0'
import styles from '../styles/Home.module.css'

export default function Home({ data }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Petfinder next js project</title>
        <meta name="description" content="Generated by next js and developed by Amanuel" />

      </Head>

      <Intro />
      <Services accessToken={data.access_token} />



    </div>
  )
}
export const getStaticProps = async () => {
  const params = new URLSearchParams();
  params.append("grant_type", "client_credentials")
  params.append("client_id", clientId)
  params.append("client_secret", clientSecret)
  const petFinderRes = await fetch(
    'https://api.petfinder.com/v2/oauth2/token',
    {
      method: 'POST',
      body: params
    }
  );
  const data = await petFinderRes.json()

  return {
    props: {
      data
    }
  }
}